# Generated by Django 5.2.6 on 2026-04-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="admin_status",
            field=models.CharField(
                choices=[
                    ("none", "No Status"),
                    ("under_review", "Under Review"),
                    ("planned", "Planned"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
