# Generated by Django 5.2.6 on 2026-05-02 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_admin_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="shared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="shared_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shares",
                to="posts.post",
            ),
        ),
    ]
