# Generated by Django 5.2.6 on 2026-05-01 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0002_reaction_comment_alter_reaction_kind_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="interactions.comment",
            ),
        ),
    ]
