# Generated by Django 5.2.6 on 2026-05-02 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalize_reactions(apps, schema_editor):
    Reaction = apps.get_model("interactions", "Reaction")
    db_alias = schema_editor.connection.alias
    seen = set()

    for reaction in Reaction.objects.using(db_alias).order_by("-created_at", "-id"):
        if reaction.comment_id:
            if reaction.post_id:
                Reaction.objects.using(db_alias).filter(pk=reaction.pk).update(post_id=None)
                reaction.post_id = None
            key = ("comment", reaction.comment_id, reaction.user_id)
        elif reaction.post_id:
            key = ("post", reaction.post_id, reaction.user_id)
        else:
            reaction.delete()
            continue

        if key in seen:
            reaction.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0003_alter_reaction_comment"),
        ("posts", "0002_post_admin_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reaction",
            name="unique_post_user_reaction_kind",
        ),
        migrations.RemoveConstraint(
            model_name="reaction",
            name="unique_comment_user_reaction_kind",
        ),
        migrations.AlterField(
            model_name="reaction",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="posts.post",
            ),
        ),
        migrations.RunPython(normalize_reactions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("comment__isnull", True), ("post__isnull", False)),
                    models.Q(("comment__isnull", False), ("post__isnull", True)),
                    _connector="OR",
                ),
                name="reaction_has_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("comment__isnull", True)),
                fields=("post", "user"),
                name="unique_post_user_reaction",
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("comment__isnull", False)),
                fields=("comment", "user"),
                name="unique_comment_user_reaction",
            ),
        ),
    ]
