# Generated by Django 5.2.6 on 2026-05-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "interactions",
            "0004_remove_reaction_unique_post_user_reaction_kind_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("love", "Love"),
                    ("care", "Care"),
                    ("wow", "Wow"),
                    ("sad", "Sad"),
                    ("angry", "Angry"),
                    ("haha", "Haha"),
                ],
                max_length=20,
            ),
        ),
    ]
