# Generated by Django 5.2.6 on 2026-04-26 13:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.models.CampusUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("student", "Student"), ("admin", "Admin")],
                default="student",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="student_id",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
