# Generated by Django 5.2.6 on 2026-05-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("mention_post", "Mentioned in post"),
                    ("mention_comment", "Mentioned in comment"),
                    ("reaction_post", "Reacted to post"),
                    ("comment_post", "Commented on post"),
                    ("share_post", "Shared post"),
                    ("friend_request", "Friend request"),
                    ("friend_accepted", "Friend accepted"),
                ],
                max_length=30,
            ),
        ),
    ]
